name: Trigger Pipeline
on:
  push:
    branches: [main]

permissions:
  actions: write
  contents: read

jobs:
  trigger-action:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Run Orchestration Action
        uses: koushik309/Actions/custom-processor@main
        with:
          input_data: 'Initial data from backend'
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}